[2023-04-14 21:46:43,555] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.232:5000 (Press CTRL+C to quit) - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 21:46:43,573] INFO _log() L224   * Restarting with stat - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 21:46:53,040] ERROR log_exception() L1449 Exception on /pedido [POST] - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 43, in add_pedido
    pedido = Pedido(
             ^^^^^^^
TypeError: __init__() got an unexpected keyword argument 'nome_cliente'
[2023-04-14 21:46:53,048] INFO _log() L224  127.0.0.1 - - [14/Apr/2023 21:46:53] "[35m[1mPOST /pedido HTTP/1.1[0m" 500 - - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 21:54:19,519] INFO _log() L224   * Detected change in 'E:\\Program_code\\Repo\\desenvolvimento-full-stack-1\\desenvolvimento-full-stack-basico\\aula-3\\meu_app_api\\schemas\\pedido.py', reloading - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 21:54:19,626] INFO _log() L224   * Restarting with stat - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 21:56:17,626] INFO _log() L224   * Detected change in 'E:\\Program_code\\Repo\\desenvolvimento-full-stack-1\\desenvolvimento-full-stack-basico\\aula-3\\meu_app_api\\schemas\\pedido.py', reloading - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 21:56:17,733] INFO _log() L224   * Restarting with stat - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 21:56:21,991] ERROR log_exception() L1449 Exception on /pedido [POST] - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py", line 43, in add_pedido
    pedido = Pedido(
             ^^^^^^^
TypeError: __init__() got an unexpected keyword argument 'nome_cliente'
[2023-04-14 21:56:22,001] INFO _log() L224  127.0.0.1 - - [14/Apr/2023 21:56:22] "[35m[1mPOST /pedido HTTP/1.1[0m" 500 - - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 22:01:38,503] INFO _log() L224   * Detected change in 'E:\\Program_code\\Repo\\desenvolvimento-full-stack-1\\desenvolvimento-full-stack-basico\\aula-3\\meu_app_api\\model\\pedido.py', reloading - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 22:01:38,609] INFO _log() L224   * Restarting with stat - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 22:02:57,494] WARNING add_pedido() L68   Erro ao adicionar o pedido do Cliente: 'Josiclésio Fonte Seca', Não foi possível salvar novo item :/ - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py L68  
[2023-04-14 22:02:57,496] INFO _log() L224  127.0.0.1 - - [14/Apr/2023 22:02:57] "[31m[1mPOST /pedido HTTP/1.1[0m" 400 - - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 22:04:32,319] WARNING add_pedido() L68   Erro ao adicionar o pedido do Cliente: '"Josiclésio Fonte Seca"', Não foi possível salvar novo item :/ - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\app.py L68  
[2023-04-14 22:04:32,320] INFO _log() L224  127.0.0.1 - - [14/Apr/2023 22:04:32] "[31m[1mPOST /pedido HTTP/1.1[0m" 400 - - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 22:05:32,598] INFO _log() L224   * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.232:5000 (Press CTRL+C to quit) - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
[2023-04-14 22:05:32,611] INFO _log() L224   * Restarting with stat - call_trace=E:\Program_code\Repo\desenvolvimento-full-stack-1\desenvolvimento-full-stack-basico\aula-3\meu_app_api\env\Lib\site-packages\werkzeug\_internal.py L224 
